[pytest]
testpaths = tests
python_files = test_*.py *_test.py
filterwarnings =
    error
    ignore:The anyio.abc.BlockingPortal alias is deprecated, use anyio.from_thread.BlockingPortal instead.:DeprecationWarning:anyio._lazyimport
